### PR TITLE
Add element icon size setting

### PR DESCRIPTION
**Pull request by rykersun**
Change element icon size in `config.rasi`

### CODE REVIEW

**Comment by undiabler** [comment]
Thank you for your proposal!
Can you please give more information on this pull request.
Why do you think icon settings should be related to this theme?

**Comment by rykersun** [comment]
Hello, I will add this setting because there is `show-icons: true;` in `config.rasi`, so I think it would be more perfect if I could set the size of the icon by the way.

Regards

**Comment by undiabler** [comment]
`config.rasi` is just an example how to add [nord theme](https://github.com/undiabler/nord-rofi-theme/blob/master/nord.rasi) to your own config.
The theme itself does not include any icons related configs.
If we want to specify icons sizes we need to be sure theme can support it.
For now it is not true, for example text is not centered properly with sized icons:
icons

_P/s I personally would like to see some monotone icons. But I have no clue if something like [css filters](https://developer.mozilla.org/en-US/docs/Web/CSS/filter-function) will work here._

**Comment by rykersun** [comment]
I think maybe you can try increasing the font size or reducing the icon size, I use papirus icon, when I set the icon size to 2ch, everything looks fine.

2022-09-27-180708_1920x1080_scrot

**Comment by undiabler** [comment]
Matching font, font size, icon size, icon theme, etc is more related to personal Dotfiles rather than to the Nord theme itself.
If more people will be confused with `show-icons: true;` in the example we should delete this line to keep it as simple as possible.

However, feel free to create your own Dotfiles repository with all specific configs. Your setup looks really nice!

**Pull request closed without merging**
